---
title: "Scenarios_for_GFI"
author: "Natalie Rice"
date: "12/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Base input 
input_1 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Changing yardline_100 to 50 

input_2 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 50,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Yardline_100 to 80

input_3 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 80,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Total home score to 14 (now teams are tied with 14)

input_4 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 14,
  "total_away_score" = 14,
  "posteam_score" = 14,
  "defteam_score" = 14,
  "special_teams_play" = 0,
  "away_score" = 14,
  "home_score" = 14,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```


```{r}
#Total home score to 14 (now teams are tied with 14) but further from endzone

input_5 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 50,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 14,
  "total_away_score" = 14,
  "posteam_score" = 14,
  "defteam_score" = 14,
  "special_teams_play" = 0,
  "away_score" = 14,
  "home_score" = 14,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Total away score to 27 (away team beating home team by 7)

input_6 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" =27,
  "posteam_score" = 21,
  "defteam_score" = 27,
  "special_teams_play" = 0,
  "away_score" = 27,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)

```

```{r}
#Team with possession has 1 timeout, defeding team has 2
input_7 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 1,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Team with possession has 3 timeouts, defending team has 2
input_8 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 3,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Team with possession has 0 timeouts, defending team has 2
input_9 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 0,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Team with possession has 2 timeouts, defending team has 1
input_10 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 1 
)
```

```{r}
#Team with possession has 2 timeouts, defending team has 3
input_11 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 3 
)
```

```{r}
#Team with possession has 2 timeouts, defending team has 0

input_12 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 0 
)
```

```{r}
#Yards to go changed to 2
input_13 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 2,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Yards to go changed to 7
input_14 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 7,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 600 in first half
input_15 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 600,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 600 in second half
input_16 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 600,
  "game_half" = 2,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 120 in the first half
input_17 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#Base input but with timeout = 1 (called a timeout)
input_18 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 1,
  "total_home_score" = 21,
  "total_away_score" = 3,
  "posteam_score" = 21,
  "defteam_score" = 3,
  "special_teams_play" = 0,
  "away_score" = 3,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

#Changing time remaining and home team losing 
```{r}
#half second remaining 600 in first half and home team losing
input_19 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 600,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 27,
  "posteam_score" = 21,
  "defteam_score" = 27,
  "special_teams_play" = 0,
  "away_score" = 27,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 600 in second half and home team losing 
input_20 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 600,
  "game_half" = 2,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 27,
  "posteam_score" = 21,
  "defteam_score" = 27,
  "special_teams_play" = 0,
  "away_score" = 27,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 120 in the first half and home team losing 
input_21 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 21,
  "total_away_score" = 27,
  "posteam_score" = 21,
  "defteam_score" = 27,
  "special_teams_play" = 0,
  "away_score" = 27,
  "home_score" = 21,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

#Changing time remaining and teams are tied 
```{r}
#half second remaining 600 in first half
input_22 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 600,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 14,
  "total_away_score" = 14,
  "posteam_score" = 14,
  "defteam_score" = 14,
  "special_teams_play" = 0,
  "away_score" = 14,
  "home_score" = 14,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 600 in second half
input_23 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 600,
  "game_half" = 2,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 14,
  "total_away_score" = 14,
  "posteam_score" = 14,
  "defteam_score" = 14,
  "special_teams_play" = 0,
  "away_score" = 14,
  "home_score" = 14,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```

```{r}
#half second remaining 120 in the first half
input_24 <- data.frame(
  "fourth_down_converted" = 0,
  "yardline_100" = 10,
  "half_seconds_remaining" = 120,
  "game_half" = 1,
  "goal_to_go" = 0,
  "ydstogo" = 5,
  "play_type" = 1,
  "timeout" = 0,
  "total_home_score" = 14,
  "total_away_score" = 14,
  "posteam_score" = 14,
  "defteam_score" = 14,
  "special_teams_play" = 0,
  "away_score" = 14,
  "home_score" = 14,
  "season" = 2018,
  "home_team" = "DET",
  "posteam" = "DET",
  "roof" = "dome",
  "down" = 3,
  "posteam_timeouts_remaining" = 2,
  "defteam_timeouts_remaining" = 2 
)
```
